# -*- coding: utf-8 -*-
"""suresh.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eyhjD86-LW0PaRrQYF8M7RLRif4Oooek
"""

a=17
b=17.45
c=a+b
print(c)
type(c)

a='15'
b='cyber security'
print(a+b)
print(type(a))

dt_a=122
dt_a

my_string = "I AM A CYBER SECURITY STUDENT"
my_string
#String Operations
my_string.upper()
print(my_string.lower())
print(len(my_string))
print(my_string.find('S'))
print(my_string.replace('CYBER','SURESH'))

#typecasting
# Convert float 2.99 to a int and check its type
dt_a=123
float(dt_a)
c=12.5
b=(dt_a + c)
print(b)
print(type(int(2.99)))

#Arthmetic operation expression
a=(43 / 60 * 16-41)
print(a)
print(type(a))

#List
my_list = [1,'stat', True, 10.30]
print(type(my_list))
#length of the list
print(len(my_list))
#add multiple items in list: Extend
my_list.extend(['CCC lab', "BU"])
print(my_list)
print(type(my_list))
#add single element:append
my_list.append('suresh')
print(my_list)
#add multiple items in list: Extend
my_list.extend(['suresh',"karthick"])
del(my_list[3])
print(my_list)

#add two list
list_name=['suresh','sudhan','karthick','bala'] 
list_group=['A+ve','B+ve','O+ve','AB+ve']
list_date=list_name+list_group
print(list_date)

#Objects:Dictionary
my_dict = {"Msc":"Stat", "Class": 1}
print(my_dict['Msc'])
print(my_dict.keys())

wa_corpa={'good':'gd','good morning':'gm','suresh kumar':'sk'}
wa_corpa
wa_corpa.keys()

my_dict={'good':'gd','good morning':'gm','suresh kumar':'sk'}
print(my_dict.keys())
del(my_dict['good'])
print(my_dict)

#Calculate Basicpay, Netpay,Grosspay of an Employee.
a=str(input("Enter your Name: "))
day=int(input("Enter The Number Of Day Present:"))
wages=int(input("Enter The Wages Per Day:"))
bs=wages*day
da=bs*0.40 
hra=bs*0.20
pf=bs*0.12
gs=bs+da+hra
ns=bs+hra+da-pf
print("Basic Salary:", bs)
print("Gross Salary:", gs)
print("Net Salary:", ns)

#Range of Value o to 1000 Print all Even Numbers
for num in range(0, 1000 +1):
  if num % 2== 0:
    print(num,end = " ")

#while Statement
def three():
  count=1
  num=3
  print ("The Multiplication Table of: ",num)
  while count <= 10:
    num= num * 1
    print (num * count)
    count += 1
def nine():
  count=1
  num=9
  print ("The Multiplication Table of: ",num) 
  while count <= 10:
    num= num * 1
    print (num * count)
    count += 1
three()
nine()

a =input("Please Enter Your Name: ")
python = float(input("Enter Python Marks: "))
os = float(input("Enter Os Marks: "))
network = float(input("Enter Network Marks: "))
security = float(input("Enter Security Marks: "))
cloud = float(input("Enter Cloud Marks: "))
total = python + os + network + security + cloud
average = total / 5
percentage = (total / 500) * 100
CGPA = (total) / (5.0)
print("Total Marks = %.2f"  %total)
print("Average Marks = %.2f"  %average)
print("total Percentage = %.2f"  %percentage)

wd=20 #working days
phs=250 #per hours working salary
mwh=56 #monthly working hours
et=100 #extra working time
total=mwh+et * wd
mi=total * phs #monthly income
print("Monthly Income:", mi)
ai=mi * 12 #anual Income
print("Anual Income:", ai)

a=[60, 70, 80, 90, 80]
b=[80, 100, 95, 75, 54]
c=[80, 30, 46, 54, 54]
d=[40, 25, 35, 56, 50]
ave=sum(a)/ 5
cgpa=(ave)/9.5
ave1=sum(b)/ 5
cgpa1=(ave1)/9.5
ave2=sum(c)/ 5
cgpa2=(ave2)/9.5
ave3=sum(d)/ 5
cgpa3=(ave3)/9.5
print("AVERAGE MARK:", ave , "cgpa:", cgpa)
print("AVERAGE MARK:", ave1 ,"cgpa:", cgpa1)
print("AVERAGE MARK:", ave2 ,"cgpa:", cgpa2)
print("AVERAGE MARK:", ave3 ,"cgpa:", cgpa3)

import pandas as pd
data = {
"name": ['suresh', 'vani', 'karthick', 'kalai', 'kumar'],
"father name": ['shankar', 'murugan', 'elumalai', 'siva', 'kumar'],
"date": [2005, 2002, 2002, 2010, 2000],
"status": ['son', 'daughter', 'son', 'daughter', 'son']
}
df=pd.DataFrame(data)
df['age']=2022-df['date']
df['father age']=2*df['age']
print (df)
df['father status']=df['father age'].apply (lambda X:'rtd' if X>58 else 'not retaired')
df

import matplotlib.pyplot as plt
import numpy as np

x = np.random.normal(170, 10, 250)

plt.hist(x)
plt.show()